# Vault.OS LightDM GTK greeter
# Install: sudo cp ~/Vault.OS/source/lightdm/lightdm-gtk-greeter.conf /etc/lightdm/lightdm-gtk-greeter.conf
[greeter]
background=/usr/share/backgrounds/Vault.OS/vault-111.png
user-background=false
theme-name=Vault.OS
icon-theme-name=Vault.OS
cursor-theme-name=Vault.OS
cursor-theme-size=24
font-name=Share Tech Mono 10
xft-antialias=true
xft-hintstyle=slight
round-user-image=false
hide-user-image=false
panel-position=top
clock-format=%H:%M
indicators=~host;~spacer;~clock;~spacer;~session;~a11y;~power
a11y-states=+contrast;-font;-keyboard;-reader
at-spi-enabled=true
position=50%,center 50%,center
screensaver-timeout=60
