[greeter]
theme-name=Vault.OS
icon-theme-name=Vault.OS
cursor-theme-name=Vault.OS
cursor-theme-size=24
font-name=Share Tech Mono 11
background=@HOME@/.local/share/backgrounds/Vault.OS/vault-111.png
user-background=false
default-user-image=@HOME@/.icons/Vault.OS/48x48/apps/start-here.png
hide-user-image=false
clock-format=%H:%M
indicators=~host;~spacer;~clock;~spacer;~session;~power
