[greeter]
theme-name=PipBoy-NV
icon-theme-name=FalloutMojave
cursor-theme-name=PipBoy-NV-Cursors
cursor-theme-size=24
font-name=Share Tech Mono 11
background=@HOME@/.local/share/backgrounds/fnv-mojave-strip-4k.jpg
user-background=false
default-user-image=@HOME@/.local/share/icons/FalloutMojave/128x128/apps/pipboy.png
hide-user-image=false
clock-format=%H:%M
indicators=~host;~spacer;~clock;~spacer;~session;~power
xft-antialias=true
xft-hintstyle=hintslight
xft-rgba=rgb
