GTK_THEME=PipBoy-NV
QT_QPA_PLATFORMTHEME=qt5ct
QT_STYLE_OVERRIDE=kvantum
XCURSOR_THEME=PipBoy-NV-Cursors
XCURSOR_SIZE=24
GTK_MODULES=canberra-gtk-module
LIBVA_DRIVER_NAME=iHD
LIBVA_DRIVERS_PATH=/usr/lib/dri
MOZ_X11_EGL=1
