# Vault.OS user seed (copied from /etc/skel on first account create)
THEME_NAME=Vault.OS
ICON_THEME=Vault.OS
WM_THEME=Vault.OS
CURSOR_THEME=Vault.OS
CURSOR_SIZE=24
UI_FONT=Share Tech Mono 10
MONO_FONT=Share Tech Mono 10
TITLE_FONT=Share Tech Mono Bold 10
