// vaultos-chromium-theme — force the Pip-Boy Chromium theme (never stock GTK).
// Native port of bin/vault-os-chromium-theme, same behaviour:
//   * does nothing while chromium runs (it would overwrite Preferences on exit)
//   * does nothing unless Preferences and the theme manifest both exist
//   * copies the theme manifest into the profile's Extensions dir
//   * registers the extension, selects it as theme (system_theme 0), drops
//     autogenerated.theme, writes Preferences atomically (tmp + fsync + rename)
// Output JSON matches Python's json.dump(separators=(",", ":")): compact,
// key order kept, non-ASCII escaped as \uXXXX.
#include <dirent.h>
#include <fcntl.h>
#include <sys/stat.h>
#include <unistd.h>
#include <cerrno>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctime>
#include <fstream>
#include <iostream>
#include <nlohmann/json.hpp>
#include <sstream>
#include <string>
#include <sys/time.h>
#include "paths.hpp"

using json = nlohmann::ordered_json;

namespace {

constexpr const char* kExtId = "kejkfoiccfnilemcanijoigaomglbkaa";

bool chromium_running() {  // pgrep -x chromium
  DIR* d = opendir("/proc");
  if (!d) return false;
  bool found = false;
  while (dirent* e = readdir(d)) {
    if (e->d_name[0] < '0' || e->d_name[0] > '9') continue;
    std::ifstream f(std::string("/proc/") + e->d_name + "/comm");
    std::string comm;
    if (f && std::getline(f, comm) && comm == "chromium") {
      found = true;
      break;
    }
  }
  closedir(d);
  return found;
}

bool is_regular(const std::string& p) {
  struct stat st{};
  return stat(p.c_str(), &st) == 0 && S_ISREG(st.st_mode);
}

bool mkdir_p(const std::string& path) {
  std::string cur;
  std::stringstream ss(path);
  std::string part;
  if (!path.empty() && path[0] == '/') cur = "/";
  while (std::getline(ss, part, '/')) {
    if (part.empty()) continue;
    cur += part + "/";
    if (mkdir(cur.c_str(), 0777) != 0 && errno != EEXIST) return false;
  }
  return true;
}

bool read_file(const std::string& p, std::string* out) {
  std::ifstream f(p, std::ios::binary);
  if (!f) return false;
  std::ostringstream ss;
  ss << f.rdbuf();
  *out = ss.str();
  return true;
}

bool write_file(const std::string& p, const std::string& data, bool sync) {
  int fd = open(p.c_str(), O_WRONLY | O_CREAT | O_TRUNC | O_CLOEXEC, 0666);
  if (fd < 0) return false;
  const char* b = data.data();
  size_t left = data.size();
  while (left) {
    ssize_t n = write(fd, b, left);
    if (n < 0) {
      if (errno == EINTR) continue;
      close(fd);
      return false;
    }
    b += n;
    left -= size_t(n);
  }
  if (sync && fsync(fd) != 0) {
    close(fd);
    return false;
  }
  return close(fd) == 0;
}

json empty_perms() {
  return json{{"api", json::array()},
              {"explicit_host", json::array()},
              {"manifest_permissions", json::array()},
              {"scriptable_host", json::array()}};
}

int fail(const std::string& msg) {
  std::fprintf(stderr, "vaultos-chromium-theme: %s\n", msg.c_str());
  return 1;
}

}  // namespace

int main() {
  const std::string home = vaultos::home();
  const std::string pref = home + "/.config/chromium/Default/Preferences";
  const char* xdh = std::getenv("XDG_DATA_HOME");
  std::string data_home = xdh ? (*xdh ? xdh : ".") : home + "/.local/share";
  const std::string theme_src = data_home + "/chromium-extensions/pipboy-nv-theme";
  const std::string ext_path = home + "/.config/chromium/Default/Extensions/" + kExtId + "/1.0.2_0";

  if (chromium_running()) return 0;
  if (!is_regular(pref) || !is_regular(theme_src + "/manifest.json")) return 0;

  if (!mkdir_p(ext_path)) return fail("cannot create " + ext_path);
  std::string manifest_text;
  if (!read_file(theme_src + "/manifest.json", &manifest_text)) return fail("cannot read theme manifest");
  if (!write_file(ext_path + "/manifest.json", manifest_text, false)) return fail("cannot write extension manifest");

  json data, manifest;
  try {
    std::string pref_text;
    if (!read_file(pref, &pref_text)) return fail("cannot read " + pref);
    data = json::parse(pref_text);
    manifest = json::parse(manifest_text);
  } catch (const json::exception& e) {
    return fail(std::string("bad JSON: ") + e.what());
  }
  if (!data.is_object()) return fail("Preferences is not a JSON object");

  timeval tv{};
  gettimeofday(&tv, nullptr);
  // Chrome time: microseconds since 1601-01-01 (same arithmetic as the Python).
  double secs = double(tv.tv_sec) + tv.tv_usec / 1e6 + 11644473600.0;
  std::string chrome_ts = std::to_string(static_cast<long long>(secs * 1000000.0));

  try {
    if (!data.contains("extensions")) data["extensions"] = json::object();
    json& ext = data["extensions"];
    if (!ext.is_object()) return fail("extensions is not an object");
    if (!ext.contains("settings")) ext["settings"] = json::object();
    json& settings = ext["settings"];
    if (!settings.is_object()) return fail("extensions.settings is not an object");

    settings[kExtId] = json{
        {"account_extension_type", 0},
        {"active_permissions", empty_perms()},
        {"commands", json::object()},
        {"content_settings", json::array()},
        {"creation_flags", 1},
        {"disable_reasons", json::array()},
        {"from_webstore", false},
        {"granted_permissions", empty_perms()},
        {"incognito_content_settings", json::array()},
        {"incognito_preferences", json::object()},
        {"location", 4},
        {"manifest", manifest},
        {"path", ext_path},
        {"preferences", json::object()},
        {"regular_only_preferences", json::object()},
        {"state", 1},
        {"was_installed_by_default", false},
        {"was_installed_by_oem", false},
        {"withholding_permissions", false},
        {"first_install_time", chrome_ts},
        {"last_update_time", chrome_ts},
    };
    ext["theme"] = json{{"id", kExtId}, {"system_theme", 0}};
    if (data.contains("autogenerated") && data["autogenerated"].is_object()) data["autogenerated"].erase("theme");
  } catch (const json::exception& e) {
    return fail(std::string("cannot update Preferences: ") + e.what());
  }

  std::string out = data.dump(-1, ' ', /*ensure_ascii=*/true);
  std::string tmp = pref + ".tmp";
  if (!write_file(tmp, out, true)) return fail("cannot write " + tmp);
  if (rename(tmp.c_str(), pref.c_str()) != 0) return fail("cannot replace " + pref);
  std::printf("pipboy chromium theme applied %s\n", kExtId);
  return 0;
}
